AlbumEmpresarial_WebApp/Models/ErrorViewModel.cs
namespace AlbumEmpresarial_WebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AlbumEmpresarial_WebApp/Models/FotosViewModel.cs
using AlbumEmpresarial_WebApp.Context;
using System.ComponentModel.DataAnnotations;

namespace AlbumEmpresarial_WebApp.Models
{
    public class FotosViewModel
    {
        public string Descripcion { get; set; }
        [Required]
        public string Fecha_Evento { get; set; }
        [Required]
        public string Lugar { get; set; }
        [Required]
        public string Descripcion_Evento { get; set; }
        [Required]
        public byte[] Imagen { get; set; }
    }

   
}

AlbumEmpresarial_WebApp/Controllers/HomeController.cs
using AlbumEmpresarial_WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AlbumEmpresarial_WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AlbumEmpresarial_WebApp/Controllers/InformacionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AlbumEmpresarial_WebApp.Context;
using System.Drawing;
using AlbumEmpresarial_WebApp.Models;

namespace AlbumEmpresarial_WebApp.Controllers
{
    public class InformacionController : Controller
    {
        private readonly albumfotosempresarialesContext _context;
        public InformacionController(albumfotosempresarialesContext context)
        {
            this._context = context;
        }

        // GET: Informacion
        public async Task<IActionResult> Index()
        {
            return View(await _context.Fotos.ToListAsync());
        }
        
        public static async Task<List<Foto>> TraerDatos()
        {
            albumfotosempresarialesContext context = new albumfotosempresarialesContext();
            List<Foto> fotos = new List<Foto>();
            try
            {
                var datos = await context.Fotos.Select(f => new
                {
                    Descripcion = f.Descripcion,
                    FechaEvento = f.FechaEvento,
                    Lugar = f.Lugar,
                    DescripcionEvento = f.DescripcionEvento,
                    Imagen = f.Imagen
                }).ToListAsync();
            }
            catch (Exception e)
            {

                throw;
            }
            return fotos;
        }
        
        private bool FotoExists(int id)
        {
          return _context.Fotos.Any(e => e.Id == id);
        }
    }
}

AlbumEmpresarial_WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AlbumEmpresarial_WebApp/Views/Informacion/Index.cshtml
@using AlbumEmpresarial_WebApp.Controllers
@model IEnumerable<AlbumEmpresarial_WebApp.Context.Foto>

@{
    ViewData["Title"] = "Index";
    var datos = InformacionController.TraerDatos();

}
<h1 class="text-center">Información de los datos de las Fotos</h1>

<table class="table" id="datos_fotos">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaEvento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lugar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DescripcionEvento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaEvento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lugar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DescripcionEvento)
            </td>
            <td>
                <img src="@datos" class="rounded-circle" width="60" height="60" asp-append-version="true">
            </td>
            
        </tr>
}
    </tbody>
</table>

AlbumEmpresarial_WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AlbumEmpresarial WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AlbumEmpresarial_WebApp.styles.css" asp-append-version="true" />
    @*Plugins importados *@
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" type="text/css" href="/css/responsive.bootstrap.min.css">


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AlbumEmpresarial WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Informacion" asp-action="Index">Informacion</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Deyson Venté - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)


    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>

</body>
</html>